### ISSUE TITLE
some question about ThreadPool?

### ISSUE THREAD

**Issue by chengdonglin** [SerayaEryn/worker-thread-pool#3]
If I create a threads pool?  each thread have the  competition problem?  
the following code have use the 4 workers  cost my tasks or only one thread works to run?Thanks?

const Pool = require('worker-thread-pool')
const pool = new Pool({
    path:__dirname+'/worker.js'
})
const tasks = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n']
let result =[]
async function main(tasks,result){
    for(let i=0;i<tasks.length;i++){
        const res = await pool.run({name:tasks[i]})
        delete tasks[i]  
        console.log(tasks) 
        result.push(res)
    }
    return result
}
const res = main(tasks,result)
res.then(data=>{
    if(data.length == tasks.length){
        //pool.close() //close the pool
    }
})

**Comment by SerayaEryn** [comment]
In your example only one thread is being used because `await pool.run()` is being called in the loop.

To use more than one thread of the pool `Promise.all()` needs to be used:

```js
const promises = tasks.map((task) => pool.run({name:task}))
const results = await Promise.all(promises)
```
